spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: ENC(arBCNLsq589b5kelutIiOcjEhlKYdFEt)
    password: ENC(BOwjc20iff3lK+YS6idjrCV83AGpIauP)
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
jasypt:
  encryptor:
    password: password1
string: prod