spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: ENC(34pwCTvoKJ6UwdtZeaWUjNEsZP0aSNTB)
    password: ENC(BOwjc20iff3lK+YS6idjrCV83AGpIauP)
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
jasypt:
  encryptor:
    password: password1
string: dev
#    properties:
 #     javax:
  #      persistence:
   #       schema-generation:
    #        create-source: metadata
     #       scripts:
      #        action: create
       #       create-target: guru_database_create.sql